### ISSUE TITLE
Couldn't delete product from wishlist

### ISSUE THREAD

**Issue by shiva-p17** [zakhardage/Shopify-Wish-List#11]
When ever I delete a product from the wished list, it's not deleting and I noticed that the 'x' length of span is keep on increasing,
`<span class="remove" data="**xxxxxx**6401784835">or remove</span>`

Can you help me with this.

**Comment by luco** [comment]
+1

**Comment by zakhardage** [comment]
Since the contact form only _adds_ customer tags, the 'x' length increases even when you remove products. Whether or not an item is in the wishlist is determined by the number of 'x's -- if it's an odd number, it's in; if it's an even number, it's out.
