### ISSUE TITLE
Wishlist Item Count

### ISSUE THREAD

**Issue by joemottershaw** [zakhardage/Shopify-Wish-List#5]
Hi, this is a great little hack for an App-less version of a wishlist, I'm going to be using it in my future themes and was just wondering if there is a way of performing a wishlist product count, separate from the current code?

For example, in the header of my page I would like to have "Wishlist - X Item(s)" where I could also then do a check on 'page.wishlist' to see if the "email to a friend" link should be displayed or not.

**Comment by alvinbond85** [comment]
This snippet didn't work for me :( I tried modifying it but to no avail, as liquid is not my strong suit. Any chance you can take a closer look Zak?

**Comment by NatalieNata** [comment]
I know this chat is closed ,but  just wanted to thank you zakhardage for the idea about  snippet from Wishlist page ! I created  a beautiful perfectly working Wishlist counter on my website!
