### ISSUE TITLE
Liquid Error: Memory Limits Exceeded

### ISSUE THREAD

**Issue by vo85** [zakhardage/Shopify-Wish-List#9]
How does one go about clearing the memory on customer.tags to empty out all items in the "Wish List"? I am using a duplicate theme to test out this widget, but have hit a wall with "Liquid error: memory limits exceeded" and can no longer proceed in seeing my edits. Please help.

**Comment by zakhardage** [comment]
You'd need to clear them manually from the shop admin or you could play a little guess-and-check by adding a limit in the customer.tags forloop. The wish list uses nested loops to compare so if a customer gets excited with it, you can grow the calculations out pretty quickly.
